name: Security Scan

on:
  schedule:
    - cron: '0 0 * * 0'  # u0417u0430u043fu0443u0441u043a u043au0430u0436u0434u043eu0435 u0432u043eu0441u043au0440u0435u0441u0435u043du044cu0435 u0432 00:00 UTC
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4

      - name: Build image
        run: docker build -t typesense:local .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # master
        with:
          image-ref: 'typesense:local'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@e4fba868fa4b1b91e1fdab776edc8cfbe6e9fb81 # v3
        with:
          sarif_file: 'trivy-results.sarif'
